#!/usr/bin/env node
/* Generate the standalone site from the same React markup as the Next.js app.
 * TypeScript is already a project dependency; no second bundler is needed.
 */
const fs = require("node:fs");
const path = require("node:path");
const ts = require("typescript");
const React = require("react");
const { renderToStaticMarkup } = require("react-dom/server");
const root = path.resolve(__dirname, "..");
const originals = {
  ".ts": require.extensions[".ts"],
  ".tsx": require.extensions[".tsx"],
};
for (const ext of [".ts", ".tsx"]) {
  require.extensions[ext] = (module, filename) => {
    const output = ts.transpileModule(fs.readFileSync(filename, "utf8"), {
      fileName: filename,
      compilerOptions: {
        module: ts.ModuleKind.CommonJS,
        jsx: ts.JsxEmit.ReactJSX,
        target: ts.ScriptTarget.ES2020,
        esModuleInterop: true,
      },
    });
    module._compile(output.outputText, filename);
  };
}
const Experience =
  require("../components/experience/LiteraryExperience.tsx").default;
const { book } = require("../lib/book-content.ts");
const { introBootstrap } = require("../lib/intro-bootstrap.ts");
const escape = (text) =>
  String(text).replace(
    /[&<>"']/g,
    (char) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[
        char
      ],
  );
const title = `${book.title} — Dhruva Nerella & Tattva Nerella`;
const description =
  "A literary companion for the climb. Discover Still Standing, Still Here by Dhruva Nerella and Tattva Nerella: its themes, chapter guide, reader voices, and where to buy the book.";
const schema = JSON.stringify({
  "@context": "https://schema.org",
  "@type": "Book",
  name: book.title,
  author: book.authors.map((name) => ({ "@type": "Person", name })),
  isbn: book.isbn,
  image: book.cover,
  url: "https://still-standing-still-here.netlify.app/",
}).replace(/</g, "\\u003c");
const html = `<!DOCTYPE html>
<!-- Generated by npm run build:static. Edit shared components/content/styles instead. -->
<html lang="en"><head>
<meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1" />
<script>${introBootstrap}</script>
<title>${escape(title)}</title><meta name="description" content="${escape(description)}" />
<link rel="canonical" href="https://still-standing-still-here.netlify.app/" />
<link rel="icon" href="public/favicon.png" type="image/png" />
<link rel="preload" href="public/fonts/cormorant-garamond-latin-wght-normal.woff2" as="font" type="font/woff2" crossorigin />
<link rel="preload" href="public/fonts/inter-latin-wght-normal.woff2" as="font" type="font/woff2" crossorigin />
<link rel="stylesheet" href="public/experience.css" />
<meta property="og:type" content="website" /><meta property="og:title" content="${escape(title)}" />
<meta property="og:description" content="${escape(description)}" /><meta property="og:url" content="https://still-standing-still-here.netlify.app/" />
<meta property="og:image" content="${escape(book.cover)}" /><meta property="og:image:alt" content="Cover of ${escape(book.title)}" />
<meta name="twitter:card" content="summary_large_image" /><meta name="twitter:image" content="${escape(book.cover)}" />
<script type="application/ld+json">${schema}</script>
<script src="public/experience.js" defer></script>
<script src="public/book-journey.js" defer></script>
</head><body>${renderToStaticMarkup(React.createElement(Experience, { assetBase: "public" }))}</body></html>
`;
fs.writeFileSync(path.join(root, "index.html"), html);
for (const ext of [".ts", ".tsx"]) {
  if (originals[ext]) require.extensions[ext] = originals[ext];
  else delete require.extensions[ext];
}
console.log("Generated index.html from the shared literary experience.");
