// Real existing sections only. Each has its own rhythm, object arrangement and path.
export const CHAPTERS = [
  {
    id: "inside",
    name: "The book",
    selectors: [
      ".book-introduction > .eyebrow",
      ".book-introduction > h2",
      ".book-introduction > .lead-copy",
      ".book-introduction > .body-copy",
      ".book-introduction > .purchase-links",
      ".book-introduction > a",
    ],
    combine: [
      [0, 1, 2],
      [4, 5],
    ],
    motif: "cover",
    sway: 0.12,
  },
  {
    id: "themes",
    name: "The meaning",
    selectors: [".meaning-heading", ".theme-row", ".meaning-footnote"],
    attachLast: [2],
    motif: "pillars",
    sway: 0.38,
  },
  {
    id: "pages",
    name: "Inside the pages",
    selectors: [".pages-intro", ".reading-preview"],
    motif: "leaves",
    sway: -0.25,
  },
  {
    id: "chapters",
    name: "The chapter journey",
    selectors: [
      ".chapter-header",
      ".chapter-tabs",
      ".chapter-panels",
      ".chapter-footer",
    ],
    combine: [1, 2, 3],
    motif: "steps",
    sway: 0.24,
  },
  {
    id: "authors",
    name: "Behind the pages",
    selectors: [".authors-copy", ".author-monogram"],
    motif: "voices",
    sway: -0.3,
  },
  {
    id: "voices",
    name: "Reader responses",
    selectors: [".reviews-header", ".reader-review"],
    motif: "quotes",
    sway: 0.28,
  },
  {
    id: "buy",
    name: "Into the light",
    selectors: [".final-content"],
    motif: "summit",
    sway: 0,
  },
];
